---
- name: Ensure ipfs cluster secret is defined
  ansible.builtin.assert:
    that:
      - ipfs_cluster_secret is defined

- name: Ensure ipfs cluster config directory
  ansible.builtin.file:
    dest: "{{ ipfs_home }}/.ipfs-cluster"
    owner: ipfs
    group: ipfs
    mode: 0750
    state: directory

- name: Config absent - run ipfs-cluster-service init
  become: true
  become_user: ipfs
  ansible.builtin.command: >
    /usr/bin/env CLUSTER_SECRET={{ ipfs_cluster_secret }} /usr/local/bin/ipfs-cluster-service init
    --peers {{ ipfs_cluster_bootstrap | join(',') }}
  args:
    chdir: "{{ ipfs_home }}"
    creates: "{{ ipfs_home }}/.ipfs-cluster/service.json"
  when: ipfs_cluster_config is not defined and ipfs_cluster_identity is not defined

- name: Ipfs cluster identity config present - output identity file
  when: ipfs_cluster_identity is defined
  block:
    - name: Check if ipfs_cluster_identity contains required fields
      ansible.builtin.assert:
        that:
          - ipfs_cluster_identity.id is defined
          - ipfs_cluster_identity.private_key is defined

    - name: Upfs cluster identity file
      ansible.builtin.copy:
        dest: "{{ ipfs_home }}/.ipfs-cluster/identity.json"
        content: "{{ ipfs_cluster_identity | to_nice_json }}"
        owner: ipfs
        group: ipfs
        mode: 0640
      notify:
        - Ipfs-cluster restart

- name: Ipfs cluster config present - output config file
  when: hostvars[inventory_hostname]['ipfs_cluster_config'] is defined
  block:
    - name: Combine user config with default config
      ansible.builtin.set_fact:
        ipfs_cluster_config_combined: >
          {{ ipfs_cluster_config_default | default({})
          | combine (hostvars[inventory_hostname]['ipfs_cluster_config'], recursive=True) }}

    - name: Combine user config with cluster secret
      ansible.builtin.set_fact:
        ipfs_cluster_config_combined: >
          {{ ipfs_cluster_config_combined  | combine ( {"cluster": {"secret": ipfs_cluster_secret } }, recursive=True ) }}

    - name: Debug merged config
      ansible.builtin.debug: var=ipfs_cluster_config_combined
      when: ipfs_config_debug

    - name: Ipfs cluster config file
      ansible.builtin.copy:
        dest: "{{ ipfs_home }}/.ipfs-cluster/service.json"
        content: "{{ ipfs_cluster_config_combined | to_nice_json }}"
        owner: ipfs
        group: ipfs
        mode: 0640
      notify:
        - Ipfs-cluster restart

- name: Ipfs-cluster service file
  ansible.builtin.template:
    src: templates/cluster/service.j2
    dest: /etc/systemd/system/ipfs-cluster.service
    owner: root
    group: root
    mode: 0644

- name: Ipfs-cluster apparmor profile
  when: use_apparmor
  ansible.builtin.template:
    src: templates/cluster/apparmor.j2
    dest: /etc/apparmor.d/ipfs-cluster
    owner: root
    group: root
    mode: 0644
  notify:
    - Load ipfs-cluster apparmor

- name: Ipfs-cluster service
  tags: molecule-notest
  ansible.builtin.service:
    name: ipfs-cluster
    state: "{{ ipfs_cluster_service_state }}"
    enabled: "{{ ipfs_cluster_service_enabled }}"
