---
- name: init ipfs user
  user:
    name: ipfs
    home: "{{ ipfs_home }}"
    password_lock: true

- name: ensure ipfs config directory
  file:
    dest: "{{ ipfs_home }}/.ipfs"
    owner: ipfs
    group: ipfs
    mode: 0750

- name: config absent - ipfs init
  become: true
  become_user: ipfs
  command: "/usr/local/bin/ipfs init --empty-repo"
  args:
    chdir: "{{ ipfs_home }}"
    creates: "{{ ipfs_home }}/.ipfs/config.json"
  when: hostvars[inventory_hostname]['ipfs_config'] is not defined

- name: config present - build ipfs config
  when: hostvars[inventory_hostname]['ipfs_config'] is defined
  block:
    - name: combine user config with default config
      set_fact:
        ipfs_config_combined: "{{ ipfs_config_default | default({}) | combine ( hostvars[inventory_hostname]['ipfs_config'], recursive=True ) }}"
  
    - name: debug merged config
      debug: var=ipfs_config_combined
      when: ipfs_config_debug

    - name: check if ipfs keys were defined
      assert:
        that:
          - ipfs_config_combined.Identity.PeerID is defined
          - ipfs_config_combined.Identity.PrivKey is defined
        fail_msg: "`ipfs_config.Identity.PeerID` and `ipfs_config.Identity.PeerID` must be defined."

    - name: write ipfs config
      copy:
        dest: "{{ ipfs_home }}/.ipfs/config"
        content: "{{ ipfs_config_combined | to_nice_json }}"
        owner: ipfs
        group: ipfs
        mode: 0640
      notify:
        - ipfs restart

- name: ipfs service file
  template:
    src: templates/ipfs/service.j2
    dest: /etc/systemd/system/ipfs.service
    owner: root
    group: root
    mode: 0644

- name: ipfs apparmor profile
  template:
    src: templates/ipfs/apparmor.j2
    dest: /etc/apparmor.d/ipfs
    owner: root
    group: root
    mode: 0644
  notify:
    - load ipfs apparmor

- name: ipfs service
  service:
    name: ipfs
    state: "{{ ipfs_service_state }}"
    enabled: "{{ ipfs_service_enabled }}"

