---
- name: init ipfs user
  user:
    name: ipfs

- name: ipfs config
  copy:
    dest: "{{ ipfs_home }}/.ipfs/config"
    content: "{{ ipfs_config_combined | to_nice_json }}"
    owner: ipfs
    group: ipfs
    mode: 0640
  notify:
    - ipfs restart

- name: ipfs service file
  template:
    src: templates/ipfs/service.j2
    dest: /etc/systemd/system/ipfs.service
    owner: root
    group: root
    mode: 0644

- name: ipfs apparmor profile
  template:
    src: templates/ipfs/apparmor.j2
    dest: /etc/apparmor.d/ipfs
    owner: root
    group: root
    mode: 0644
  notify:
    - load ipfs apparmor

- name: ipfs service
  service:
    name: ipfs
    state: started
    enabled: true

