---
- name: configure ipfs service
  include_tasks: tasks/ipfs.yaml

- name: configure ipfs cluster
  include_tasks: tasks/clust.yaml
  when: ipfs_cluster_secret is defined and ipfs_cluster_bootstrap is defined