---
- name: Check if apparmor is used
  ansible.builtin.stat:
    path: /etc/apparmor.d
  register: aa

- name: Set apparmor status
  ansible.builtin.set_fact:
    use_apparmor: "{{ aa.stat.exists }}"

- name: Disable handlers for Docker testing
  ansible.builtin.set_fact:
    molecule_notest: true
  tags: molecule-notest

- name: Configure ipfs service
  ansible.builtin.include_tasks: tasks/ipfs.yaml

- name: Configure ipfs cluster
  ansible.builtin.include_tasks: tasks/clust.yaml
  when: ipfs_cluster_secret is defined and ipfs_cluster_bootstrap is defined
