---
- name: check if apparmor is used
  stat:
    path: /etc/apparmor.d
    register: aa
- name: set apparmor status
  set_fact:
    use_apparmor: "{{ aa.stat.isdir }}"

- name: configure ipfs service
  include_tasks: tasks/ipfs.yaml

- name: configure ipfs cluster
  include_tasks: tasks/clust.yaml
  when: ipfs_cluster_secret is defined and ipfs_cluster_bootstrap is defined