---
- name: ipfs restart
  when: molecule_notest | default(false)
  service:
    name: ipfs.service
    state: restarted

- name: ipfs-cluster restart
  when: molecule_notest | default(false)
  service:
    name: ipfs-cluster.service
    state: restarted

- name: load ipfs apparmor
  when: molecule_notest | default(false)
  command: /sbin/apparmor_parser -r -W /etc/apparmor.d/ipfs

- name: load ipfs-cluster apparmor
  when: molecule_notest | default(false)
  command: /sbin/apparmor_parser -r -W /etc/apparmor.d/ipfs-cluster

