
---
- name: Converge
  hosts: all
  roles:
    - role: kravietz.ipfs_config
      ipfs_config:
        Identity:
          PeerID: 12D3KooWC63dS6HaKjMydDRvvPpFdaZHkmRfCixhK6zAgEpFYLUW
          PrivKey: CAESQGAx3NTE6ZJSlmtiI1OAoMGOP2GfuxevjGTRWj9ZEgVuIbu0J4Se4lknO8MKUQQVLjnTHKHDzcMm9Ofp6l36+78=
