---
name: molecule

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - uses: MonolithProjects/action-molecule@v1.4.5
        with:
          molecule_command: converge
